### ISSUE TITLE
can not start  selfforwarder

### ISSUE THREAD

**Issue by mightymeyti** [Nirzak/Self-Forwarder-Bot#1]
### when running selfforwarder, the follwing error shows:

Traceback (most recent call last):
  File "/usr/local/bin/selfforwarder", line 5, in <module>
    from selfforwarder.__main__ import main
  File "/usr/local/lib/python3.8/dist-packages/selfforwarder/__main__.py", line 5, in <module>
    from selfforwarder import commands
  File "/usr/local/lib/python3.8/dist-packages/selfforwarder/commands.py", line 1, in <module>
    from selfforwarder import utils
  File "/usr/local/lib/python3.8/dist-packages/selfforwarder/utils.py", line 4, in <module>
    from telegram.ext.dispatcher import run_async
ModuleNotFoundError: No module named 'telegram.ext.dispatcher'

**Comment by Nirzak** [comment]
Have to check by running again.

**Comment by Nirzak** [comment]
Sorry I was busy on other things. So couldn't focus on this. The issue has been fixed. Thanks for the report.
